application: pebble-netatmo
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /auth.*
  script: gae.auth.application
- url: /config.*
  script: gae.netatmo.application
- url: /
  script: gae.netatmo.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest